local icons = {
    ui = require("configs.ui.icons").get("ui"),
    diagnostics = require("configs.ui.icons").get("diagnostics"),
}

require("trouble").setup({
    position = "bottom",
    height = 10,
    width = 50,
    icons = true,
    mode = "document_diagnostics",
    fold_open = icons.ui.ArrowOpen,
    fold_closed = icons.ui.ArrowClosed,
    action_keys = {
        close = "q",
        cancel = "<esc>",
        refresh = "r",
        jump = { "<cr>", "<tab>" },
        open_split = { "<c-x>" },
        open_vsplit = { "<c-v>" },
        open_tab = { "<c-t>" },
        jump_close = { "o" },
        toggle_mode = "m",
        toggle_preview = "P",
        hover = "K",
        preview = "p",
        close_folds = { "zM", "zm" },
        open_folds = { "zR", "zr" },
        toggle_fold = { "zA", "za" },
        previous = "k",
        next = "j",
    },
    indent_lines = true,
    auto_open = false,
    auto_close = false,
    auto_preview = true,
    auto_fold = false,
    signs = {
        error = icons.diagnostics.Error_alt,
        warning = icons.diagnostics.Warning_alt,
        hint = icons.diagnostics.Hint_alt,
        information = icons.diagnostics.Information_alt,
        other = icons.diagnostics.Question_alt,
    },
    use_lsp_diagnostic_signs = false,
})
